export type Gear = 'Quick' | 'Guided' | 'Deep';
export type Concept = {id:string;title:string;label:string;summary:string;detail:string;example:string;question:string;choices:string[];answer:number;why:string};
export type LearningMap = {id:string;title:string;kicker:string;description:string;source:{title:string;url:string};concepts:Concept[]};
const c=(id:string,title:string,label:string,summary:string,detail:string,example:string,question:string,choices:string[],answer:number,why:string):Concept=>({id,title,label,summary,detail,example,question,choices,answer,why});
export const maps:LearningMap[]=[{
 id:'systems',title:'Thinking in systems',kicker:'SEE THE BIGGER PICTURE',description:'Connections, patterns, and the world between.',source:{title:'The Systems Thinker · Systems thinking',url:'https://thesystemsthinker.com/systems-thinking-what-why-when-where-and-how/'},concepts:[
 c('whole','The whole & its parts','Start here','A system is a collection of connected parts whose interactions produce a pattern of behavior.','Understanding each part is useful, but it is not enough. The relationships between parts can explain behavior that no single part produces on its own. The boundary you choose determines what you treat as inside the system and what you leave in its environment.','A bicycle needs wheels, pedals, a chain, and a frame. A pile of those parts does not carry you anywhere. Their arrangement and interaction make riding possible.','What makes a collection of parts a system?',['The number of parts','The interactions between the parts','The size of each part'],1,'Relationships matter: the parts must interact to produce the behavior we are studying.'),
 c('connections','Connections','A change travels','The effect of a change depends on how one part is connected to the others.','Some connections carry material, others carry information. Changing an information flow can change decisions even when the physical parts stay the same. A connection is a proposed explanation, not proof of causation; it needs evidence in a real system.','A thermostat connects room temperature to a heating decision. Without that information, the heater cannot respond to the room.','Which connection carries information?',['A pipe carrying water','A thermometer reporting temperature','A belt moving a wheel'],1,'A temperature reading changes what the controller knows. The pipe and belt transfer physical quantities.'),
 c('stocks','Stocks & flows','What builds up','A stock is something that accumulates. Flows add to it or take away from it.','The amount in a stock changes according to the difference between inflows and outflows over time. A stock can keep increasing even while its inflow is falling, if that inflow is still greater than the outflow.','A bathtub holds a stock of water. The tap is an inflow and the drain is an outflow. If 5 liters enter and 3 leave each minute, the stock grows by 2 liters per minute.','If 5 liters enter and 3 leave each minute, what happens?',['Water rises by 2 liters per minute','Water falls by 2 liters per minute','Water stays constant'],0,'Net change is inflow minus outflow: 5 − 3 = 2 liters per minute.'),
 c('feedback','Feedback loops','When effects return','A feedback loop exists when the result of an action comes back to influence that action.','Trace the chain of effects until it returns to its starting point. A reinforcing loop amplifies a change. A balancing loop counteracts it. Neither label means good or bad; both kinds can help or hurt depending on the context.','You practice a skill, become more confident, and choose to practice more. That is a possible reinforcing loop. Fatigue can eventually introduce a balancing effect.','What makes feedback a loop?',['An effect returns to influence its cause','Two events occur together','An action has no consequences'],0,'Feedback closes the chain: a downstream effect changes what happens at the starting point.'),
 c('balance','Finding balance','A target to return to','A balancing loop responds to a difference between the current state and a target.','As the gap narrows, the corrective action usually becomes smaller. Delays or overly strong corrections can cause oscillation instead of a smooth approach to the target. Balance describes the direction of feedback, not a guarantee of stability.','A thermostat turns on heating when a room is too cold and turns it off when the target temperature is reached.','A thermostat switching off heating at its target is an example of…',['Reinforcing feedback','Balancing feedback','No feedback'],1,'The response reduces the gap between actual and desired temperature.'),
 c('delays','Delays','The space before a result','A delay is the time between an action and its observable effect.','If you react before an earlier action has had time to work, you may overcorrect. The appropriate response depends on the size and variability of the delay, not just the current gap.','You turn a shower toward hot, feel no immediate change, and turn it further. When the hot water arrives, it is much hotter than you intended.','Why can repeated adjustments make a delayed system overshoot?',['Earlier actions have not finished taking effect','Delays always stop all change','More adjustments always improve accuracy'],0,'The effects can accumulate before you observe them, so the total correction is larger than intended.'),
 c('leverage','Leverage points','Where a small change matters','A leverage point is a place where changing a system can strongly influence its behavior.','A small-looking intervention is not automatically a leverage point. You must understand the surrounding relationships and test the effect. Changing a rule or information flow may matter more than simply increasing an input.','Giving a household clear, timely information about electricity use can change decisions. Whether it reduces consumption depends on how people respond.','What should you do before calling an intervention a leverage point?',['Assume small changes always work','Examine and test its effect on the system','Ignore the surrounding relationships'],1,'Leverage depends on the system and evidence, not the apparent size of the intervention.')
 ]},
 {id:'light',title:'The language of light',kicker:'EXPLORE THE EVERYDAY',description:'From a single wave to everything we see.',source:{title:'OpenStax · University Physics, Volume 3',url:'https://openstax.org/details/books/university-physics-volume-3'},concepts:[
 c('waves','Light as a wave','Start here','Light is electromagnetic radiation. A wave model helps explain how it travels and interacts.','In a vacuum, light travels at the same speed regardless of visible color. Its wavelength and frequency are related by speed = wavelength × frequency. The wave model explains interference and diffraction; some other interactions require a photon model.','Red visible light has a longer wavelength and lower frequency than violet visible light in a vacuum.','In a vacuum, a shorter wavelength corresponds to…',['Lower frequency','Higher frequency','No frequency'],1,'The speed is fixed, so wavelength and frequency vary inversely.'),
 c('spectrum','The spectrum','Beyond what we see','Visible light is a small part of the electromagnetic spectrum.','Radio waves, microwaves, infrared, visible light, ultraviolet, X-rays, and gamma rays belong to the electromagnetic spectrum. These categories describe ranges of frequency and wavelength rather than different kinds of basic wave.','A remote control can use infrared radiation that your eyes do not detect.','Is infrared part of the electromagnetic spectrum?',['Yes','No','Only when visible'],0,'Our vision covers only a limited band; electromagnetic radiation extends beyond it.'),
 c('reflection','Reflection','A change of direction','Reflection occurs when light returns from a boundary into the medium it came from.','For specular reflection, the angle of incidence equals the angle of reflection, both measured from the normal to the surface. Rough surfaces scatter reflected light in many directions because their local orientations vary.','A smooth mirror creates a recognizable image. A sheet of paper reflects light too, but scatters it over many directions.','Reflection angles are measured from…',['The surface itself','The normal to the surface','Any arbitrary direction'],1,'The normal is perpendicular to the surface at the point where the ray arrives.'),
 c('refraction','Refraction','Across a boundary','A light ray can change direction when it crosses into a medium where its speed differs.','Snell’s law relates the angles and refractive indices at the boundary. At normal incidence, the speed can change without a change in direction. Frequency stays the same across a stationary boundary while wavelength changes.','A straw can look bent where it enters water because rays from its submerged part refract on their way to your eyes.','Must light change direction whenever its speed changes at a boundary?',['Yes, always','No, not at normal incidence','Only red light does'],1,'At normal incidence the ray continues straight even though its speed and wavelength can change.'),
 c('lenses','Lenses','Bringing rays together','A lens uses refraction at its surfaces to change the paths of light rays.','A converging lens can bring incoming parallel rays toward a focus. Image position depends on object distance and focal length. A lens does not create extra light; it redirects the light reaching it.','A magnifying glass can form a larger upright virtual image when an object is placed inside its focal length.','A lens changes ray paths mainly through…',['Refraction','Creating light','Changing the object'],0,'Its shaped interfaces refract incoming light.'),
 c('interference','Interference','When waves meet','When waves overlap, their disturbances combine. The result can be stronger or weaker.','For a stable light interference pattern, the waves need a consistent phase relationship. Constructive interference increases intensity in some regions and destructive interference decreases it in others; energy is redistributed.','Two coherent slits can produce alternating bright and dark fringes on a screen.','Dark interference fringes correspond to…',['Destructive interference','No waves arriving anywhere','Light slowing to zero'],0,'Overlapping wave contributions can cancel at particular locations.'),
 c('photons','Photons','Light in discrete exchanges','Light exchanges energy with matter in amounts associated with photons.','A photon’s energy is proportional to its frequency: E = hf. Higher intensity can mean more photons, while higher frequency means more energy per photon. Wave and photon descriptions address different aspects of observations.','For the same total energy, a beam of lower-frequency photons contains more photons than a beam of higher-frequency photons.','Which photons have greater energy individually?',['Higher-frequency photons','Lower-frequency photons','All photons have equal energy'],0,'Photon energy is proportional to frequency.')
 ]},
 {id:'calculus',title:'Foundations of calculus',kicker:'UNDERSTAND CHANGE',description:'The mathematics of things that move.',source:{title:'OpenStax · Calculus, Volume 1',url:'https://openstax.org/details/books/calculus-volume-1'},concepts:[
 c('functions','Functions','Start here','A function assigns exactly one output to each input in its domain.','Inputs outside the domain are not covered by the function. Different inputs may share an output, but one allowed input cannot have two different outputs. Graphs, tables, and formulas can all describe the same relationship.','For f(x) = x², the input 3 gives 9, and the input −3 also gives 9.','Can different inputs have the same output?',['Yes','No','Only if the function is zero'],0,'The restriction is one output per input, not one input per output.'),
 c('change','Rates of change','Compare two moments','An average rate of change compares the change in output with the change in input.','Between a and b, the average rate is [f(b) − f(a)] / (b − a), provided a and b differ. On a graph this is the slope of the secant line through the two points.','If distance increases from 10 to 30 meters over 4 seconds, average speed over that interval is 5 meters per second.','A change of 20 meters in 4 seconds gives…',['80 m/s','5 m/s','16 m/s'],1,'Divide the distance change by elapsed time: 20 / 4 = 5.'),
 c('limits','Limits','Getting closer','A limit describes what a function’s values approach as its input approaches a specified point.','A limit depends on nearby behavior, not necessarily the value at the point. A function may have a limit at a point where it is undefined. Two-sided limits require the approaches from both sides to agree.','For x ≠ 1, (x² − 1)/(x − 1) equals x + 1. Its limit as x approaches 1 is 2, even though the original expression is undefined at 1.','Must a function be defined at a point to have a limit there?',['Yes','No','Only for positive inputs'],1,'Limits describe nearby behavior; the value at the point is a separate question.'),
 c('derivatives','Derivatives','Change at an instant','A derivative measures the instantaneous rate of change of a function.','Start with an average rate over a small interval. If the difference quotient approaches a finite value as the interval shrinks to zero, that value is the derivative. Graphically it is the tangent slope. Not every function is differentiable everywhere.','For f(x) = x², the derivative is 2x. At x = 3, the tangent slope is 6.','For f(x) = x², what is the derivative at x = 3?',['3','6','9'],1,'The derivative is 2x, so at x = 3 it equals 6.'),
 c('tangents','Tangent lines','A local picture','A tangent line describes a differentiable curve’s local direction at a point.','At x = a, the tangent line is y = f(a) + f′(a)(x − a). It gives a local linear approximation. Accuracy generally changes as you move away from the point, and the approximation is not a global identity.','For x² at x = 3, the tangent line is y = 9 + 6(x − 3). At x = 3.1 it predicts 9.6; the exact value is 9.61.','A tangent approximation is intended to be used…',['Near the chosen point','Everywhere with exact accuracy','Only at infinity'],0,'It captures local behavior; the curve can depart from the line farther away.'),
 c('integrals','Integrals','Small pieces, added','A definite integral accumulates contributions over an interval.','For suitable functions, it is the limit of sums of function values multiplied by small interval widths. A signed integral can include negative contributions. Geometric area and signed accumulation are not always the same number.','Integrating a constant velocity of 5 m/s over 4 seconds gives a displacement of 20 meters.','Integrating velocity over time gives…',['Displacement','Acceleration','Temperature'],0,'Velocity multiplied by a short time interval contributes displacement; the integral accumulates it.'),
 c('connection','The connection','Two sides of change','The fundamental theorem of calculus connects differentiation with integration.','For a continuous function f, the derivative of its accumulation function F(x) = ∫ₐˣ f(t)dt is f(x). The theorem also lets us evaluate a definite integral through an antiderivative under the applicable conditions.','Because an antiderivative of 2x is x², the integral of 2x from 0 to 3 is 9 − 0 = 9.','The integral of 2x from 0 to 3 is…',['3','6','9'],2,'Use the antiderivative x² at the endpoints: 3² − 0² = 9.')
 ]}
];
export const mapEdges=[[0,1],[0,2],[1,3],[2,3],[3,4],[3,5],[4,6],[5,6]];
export const positions=[[125,170],[320,80],[320,255],[535,170],[745,75],[745,270],[950,170]];
