"use client";

import { useEffect, useRef, useState, type CSSProperties } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, ArrowUpRight, Bookmark, BookOpen, Check, ChevronRight, CircleHelp, Compass, ExternalLink, GitBranch, List, Maximize2, Minus, Network, Plus, Search, Sparkles, X } from 'lucide-react';
import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { Button } from '@/components/ui/button';
import { LearnChat } from '@/components/learn-chat';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { maps, mapEdges, positions, type Concept, type Gear, type LearningMap } from '@/lib/learning-content';
import { type LessonArtifact } from '@/lib/api';

type Branch = { id:string;mapId:string;conceptId:string;anchor:string;mode:string;parent:string|null;draft:string;note:string };
type Stored = {version:1;mapId:string|null;conceptId:string;gear:Gear;visited:string[];branches:Branch[];saved:string[];ideas:string[]};
const INITIAL:Stored={version:1,mapId:null,conceptId:'whole',gear:'Guided',visited:[],branches:[],saved:[],ideas:[]};
const STORAGE='forma-workspace-v1';
const validGear=(v:string):v is Gear=>['Quick','Guided','Deep'].includes(v);

function MiniMap({index}:{index:number}){
 return <div className={'mini-map map-color-'+index}><svg viewBox="0 0 250 100" aria-hidden="true"><path d="M50 58 L105 30 L159 62 L209 33 M105 30 L119 82 M159 62 L119 82 M50 58 L119 82"/>{[[50,58],[105,30],[159,62],[209,33],[119,82]].map(([x,y],j)=><circle key={j} cx={x} cy={y} r={j===2?8:5}/>)}</svg><span>0{index+1}</span></div>
}


export default function LearningWorkspace(){
 const [state,setState]=useState<Stored>(INITIAL);
 const [learnVersion,setLearnVersion]=useState(0);
 const [ready,setReady]=useState(false);
 const [view,setView]=useState<'home'|'maps'|'saved'|'topic'>('home');
 const [mode,setMode]=useState('map');
 const [topic]=useState('');
 const [query,setQuery]=useState('');
 const [dialog,setDialog]=useState<'about'|'topic'|null>(null);
 const [sources,setSources]=useState(false);
 const [branchId,setBranchId]=useState<string|null>(null);
 const [zoom,setZoom]=useState(1);
 const [outline,setOutline]=useState(false);
 const [localAction,setLocalAction]=useState('');
 const [checkOpen,setCheckOpen]=useState(false);
 const [answer,setAnswer]=useState<number|null>(null);
 const [selection,setSelection]=useState('');
 const [notice,setNotice]=useState('');
 const [generatedMap]=useState<LearningMap|null>(null);

 const [assistantLesson,setAssistantLesson]=useState<LessonArtifact|null>(null);
 const lessonRef=useRef<HTMLElement>(null);
 const branchRef=useRef<HTMLHeadingElement>(null);
 const triggerRef=useRef<HTMLElement|null>(null);
 const liveState=useRef(state);
 liveState.current=state;
 const currentMap=(generatedMap?.id===state.mapId?generatedMap:null)??maps.find(m=>m.id===state.mapId)??maps[0];
 const concept=currentMap.concepts.find(c=>c.id===state.conceptId)??currentMap.concepts[0];
 const branch=state.branches.find(b=>b.id===branchId);
 const branchMap=(generatedMap?.id===branch?.mapId?generatedMap:null)??maps.find(m=>m.id===branch?.mapId)??currentMap;
 const branchConcept=branchMap.concepts.find(c=>c.id===branch?.conceptId)??concept;
 const crumbs:Branch[]=[];
 if(branch){let b:Branch|undefined=branch;let guard=0;while(b&&guard++<20){crumbs.unshift(b);b=state.branches.find(p=>p.id===b?.parent);}}

 useEffect(()=>{
  try{const raw=localStorage.getItem(STORAGE);if(raw){const d=JSON.parse(raw);if(d.version===1&&Array.isArray(d.visited)&&Array.isArray(d.branches)&&validGear(d.gear)){const strings=(a:unknown)=>Array.isArray(a)?a.filter(x=>typeof x==='string'):[];const restored={...INITIAL,mapId:maps.some(m=>m.id===d.mapId)?d.mapId:null,conceptId:typeof d.conceptId==='string'?d.conceptId:'whole',gear:d.gear,visited:strings(d.visited),branches:d.branches.filter((b:Branch)=>b&&typeof b.id==='string'&&typeof b.anchor==='string'&&typeof b.draft==='string'&&maps.some(m=>m.id===b.mapId)),saved:strings(d.saved),ideas:strings(d.ideas)};setState(restored);const ui=JSON.parse(localStorage.getItem(STORAGE+'-view')||'{}');if(['home','maps','saved','topic'].includes(ui.view)){setMode(ui.mode==='lesson'?'lesson':'map');if(restored.branches.some((b:Branch)=>b.id===ui.branchId))setBranchId(ui.branchId);}}}}catch{setNotice('Your saved workspace could not be restored. You can still explore the samples.');}setReady(true);
 },[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(STORAGE,JSON.stringify(state));}catch{setNotice('Storage is unavailable. Changes will last only for this visit.');}},[state,ready]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(STORAGE+'-view',JSON.stringify({view,mode,branchId}));}catch{}},[ready,view,mode,branchId]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timer)},[notice]);
 useEffect(()=>{if(branchId)branchRef.current?.focus()},[branchId]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setView('home');setBranchId(null);setTimeout(()=>document.getElementById('topic')?.focus(),0)}if(e.key==='Escape'&&branchId){setBranchId(null);triggerRef.current?.focus();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[branchId]);

 function openMap(id:string){const m=maps.find(x=>x.id===id);if(!m)return;setAssistantLesson(null);setState(s=>({...s,mapId:id,conceptId:s.mapId===id?s.conceptId:m.concepts[0].id}));setView('topic');setMode('map');setBranchId(null);setZoom(1);setQuery('');setSelection('');}
 function openConcept(id:string){if(!currentMap.concepts.some(c=>c.id===id))return;setState(s=>({...s,conceptId:id,visited:Array.from(new Set([...s.visited,`${currentMap.id}:${id}`]))}));setMode('lesson');setLocalAction('');setAnswer(null);setCheckOpen(false);setSelection('');setBranchId(null);}

 function openBranch(anchor:string,action='Explain',parent:string|null=null){triggerRef.current=document.activeElement as HTMLElement;const base=parent?state.branches.find(b=>b.id===parent):null;const b:Branch={id:crypto.randomUUID(),mapId:base?.mapId??currentMap.id,conceptId:base?.conceptId??concept.id,anchor:anchor.slice(0,600),mode:action,parent,draft:'',note:''};setState(s=>({...s,branches:[...s.branches,b]}));setBranchId(b.id);setSelection('');}
 function closeBranch(){setBranchId(null);setTimeout(()=>triggerRef.current?.focus(),0);}
 function saveLesson(){const id=`${currentMap.id}:${concept.id}`;setState(s=>({...s,saved:s.saved.includes(id)?s.saved.filter(x=>x!==id):[...s.saved,id]}));}
 function setGear(v:string){if(validGear(v)){setState(s=>({...s,gear:v}));setLocalAction('');}}
 function onSelection(){const sel=window.getSelection();if(sel&&sel.toString().trim()&&lessonRef.current?.contains(sel.anchorNode)){setSelection(sel.toString().trim().slice(0,600));}}
 function followBranch(){if(!branch?.draft.trim())return;const text=branch.draft.trim();const matched=branchMap.concepts.find(c=>text.toLowerCase().includes(c.title.toLowerCase()));const b:Branch={id:crypto.randomUUID(),mapId:branchMap.id,conceptId:matched?.id??branch.conceptId,anchor:text,mode:matched?'Explain':'Question',parent:branch.id,draft:'',note:matched?'':'Live answers are not connected in this preview. Here is the sample explanation for this concept; your question is saved.'};setState(s=>({...s,branches:[...s.branches.map(x=>x.id===branch.id?{...x,draft:''}:x),b]}));setBranchId(b.id);}

 useEffect(()=>{
  const ctx=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;
  if(!ctx?.registerTool)return;const lifecycle=new AbortController();
  const register=async()=>{await ctx.registerTool({name:'open_sample_learning_map',description:'Open one of the three sample learning maps in this preview. Does not generate an AI map.',inputSchema:{type:'object',properties:{mapId:{type:'string',enum:maps.map(m=>m.id)}},required:['mapId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const id=(input as {mapId?:string})?.mapId;if(!id||!maps.some(m=>m.id===id))throw new Error('Choose systems, light, or calculus.');openMap(id);await new Promise(resolve=>setTimeout(resolve,0));return{mapId:id,status:'opened',content:'sample'};}},{signal:lifecycle.signal});await ctx.registerTool({name:'read_learning_workspace',description:'Read the selected sample map, teaching gear, and locally explored concepts.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({mapId:liveState.current.mapId,conceptId:liveState.current.conceptId,gear:liveState.current.gear,explored:liveState.current.visited})},{signal:lifecycle.signal});};void register().catch(()=>{});return()=>lifecycle.abort();
 },[]);

 return <SidebarProvider style={{'--sidebar-width':'238px'} as CSSProperties}>
  <Sidebar className="forma-sidebar"><SidebarHeader><div className="brand"><Compass size={25}/>forma<SidebarTrigger className="collapse-control"/></div></SidebarHeader><SidebarContent>
   <Button variant="outline" className="new-topic" onClick={()=>{setLearnVersion(v=>v+1);setView('home');setBranchId(null);setTimeout(()=>document.getElementById('topic')?.focus(),0)}}><Plus size={16}/>New topic<span>⌘ K</span></Button>
   <button className={'nav-item '+(view==='home'||view==='topic'?'active':'')} onClick={()=>{setView('home');setBranchId(null)}}><Compass size={17}/>Learn</button>
   <div className="side-label">YOUR SPACE</div>
   <button className={'nav-item '+(view==='maps'?'active':'')} onClick={()=>{setView('maps');setBranchId(null)}}><Network size={17}/>Knowledge maps</button>
   <button className={'nav-item '+(view==='saved'?'active':'')} onClick={()=>{setView('saved');setBranchId(null)}}><BookOpen size={17}/>Saved explorations{state.saved.length+state.branches.length>0?<span className="nav-count">{state.saved.length+state.branches.length}</span>:null}</button>
   <div className="side-label">SAMPLE MAPS <span>3</span></div>{maps.map(m=><button className={'nav-item topic-nav '+(view==='topic'&&state.mapId===m.id?'current':'')} key={m.id} onClick={()=>openMap(m.id)}><span className="tiny-orbit"/>{m.title}</button>)}
  </SidebarContent><SidebarFooter><div className="sidebar-note"><span className="mini-star">✳</span><p>A little curiosity.<br/>A new way to see.</p></div><button className="profile" onClick={()=>setDialog('about')}><span className="avatar">Y</span><div>Your workspace<small>Personal · On this device</small></div><CircleHelp size={15}/></button></SidebarFooter></Sidebar>
  <main className={'workspace '+(branch?'with-branch':'')}><header className="topbar"><div><SidebarTrigger/><button onClick={()=>{setView('home');setBranchId(null)}}>Workspace</button><ChevronRight size={13}/><strong>{view==='topic'?currentMap.title:view==='saved'?'Saved explorations':view==='maps'?'Knowledge maps':'Learn'}</strong></div><button className="preview-label" onClick={()=>setDialog('about')}>Interactive preview</button></header>
  <div hidden={view!=='home'}><LearnChat key={learnVersion} /></div>
  {view==='maps'?<div className="library-content"><div className="eyebrow">YOUR SPACE</div><h1>Knowledge maps</h1><p className="intro">A growing collection of connected ideas.</p><div className="search-field"><Search size={16}/><input aria-label="Search maps" placeholder="Find a map…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="map-cards">{maps.filter(m=>m.title.toLowerCase().includes(query.toLowerCase())).map(m=><button className="map-card" key={m.id} onClick={()=>openMap(m.id)}><MiniMap index={maps.indexOf(m)}/><div className="map-card-body"><small>SAMPLE MAP</small><h3>{m.title}<ArrowUpRight size={16}/></h3><p>{m.description}</p></div></button>)}</div>{!maps.some(m=>m.title.toLowerCase().includes(query.toLowerCase()))?<div className="empty-state"><Search size={24}/><h2>No matching maps</h2><p>Try “systems”, “light”, or “calculus”.</p><Button variant="outline" onClick={()=>setQuery('')}>Clear search</Button></div>:null}{state.ideas.length>0?<section className="ideas"><h2>Ideas for later</h2><p>Saved on this device. Live map generation is not connected yet.</p>{state.ideas.map(t=><div key={t}><Sparkles size={15}/>{t}</div>)}</section>:null}</div>:null}
  {view==='saved'?<div className="library-content"><div className="eyebrow">YOUR SPACE</div><h1>Keep the useful parts.</h1><p className="intro">Saved lessons and the questions you followed.</p>{state.saved.length+state.branches.length===0?<div className="empty-state"><Bookmark size={28}/><h2>A little space for your discoveries.</h2><p>Save a lesson or open an exploration. It will be waiting here.</p><Button variant="outline" onClick={()=>setView('maps')}>Explore the maps <ArrowRight size={15}/></Button></div>:<div className="saved-list">{state.saved.map(id=>{const [mi,ci]=id.split(':');const m=maps.find(m=>m.id===mi);const c=m?.concepts.find(c=>c.id===ci);return c&&m?<button key={id} onClick={()=>{setState(s=>({...s,mapId:mi,conceptId:ci}));setView('topic');setMode('lesson')}}><Bookmark size={18}/><span><strong>{c.title}</strong><small>{m.title} · Saved lesson</small></span><ChevronRight size={16}/></button>:null})}{state.branches.map(b=><button key={b.id} onClick={()=>{setState(s=>({...s,mapId:b.mapId,conceptId:b.conceptId}));setView('topic');setMode('lesson');setBranchId(b.id)}}><GitBranch size={18}/><span><strong>{b.anchor}</strong><small>{maps.find(m=>m.id===b.mapId)?.title} · {b.mode}</small></span><ChevronRight size={16}/></button>)}</div>}</div>:null}
  {view==='topic'?<div className="topic-workspace"><div className="topic-heading"><div><span className="eyebrow">{currentMap.id.startsWith('generated:')?'LIMITED DRAFT GRAPH':'SAMPLE LEARNING MAP'}</span><h1>{currentMap.title}</h1><p>{currentMap.description}</p></div><button className="source-button" onClick={()=>setSources(true)}><BookOpen size={15}/>{currentMap.id.startsWith('generated:')?'Trust status':'Reading reference'}<ArrowUpRight size={13}/></button></div>
  {assistantLesson?<section className="chat-response" aria-label="Tutor response"><div className="chat-user-message"><span className="chat-avatar">Y</span><p>{topic}</p></div><article className="chat-assistant-message"><div className="chat-response-meta"><span className="assistant-mark"><Sparkles size={14}/></span><strong>Forma</strong><span>First lesson · {assistantLesson.gear}</span></div>{assistantLesson.blocks.filter(block=>block.kind!=='source_note').map(block=><div className="chat-block" key={block.id}>{block.heading?<h3>{block.heading}</h3>:null}<p>{block.body}</p></div>)}<div className="chat-trust-note"><CircleHelp size={14}/><span>{assistantLesson.generatedBy?.startsWith('openrouter/')?'This lesson was written with an AI model. It has no retrieved citations or independent verification, and does not update mastery.':'This first response is a deterministic scaffold with insufficient source support. It is useful for testing the learning flow and does not update mastery.'}</span></div></article></section>:null}
   <div className="topic-toolbar"><Tabs value={mode} onValueChange={v=>{setMode(v);setBranchId(null)}}><TabsList><TabsTrigger value="map"><Network size={15}/>Map</TabsTrigger><TabsTrigger value="lesson"><BookOpen size={15}/>Learn</TabsTrigger></TabsList></Tabs><span className="explored-count">{state.visited.filter(x=>x.startsWith(currentMap.id+':')).length} of {currentMap.concepts.length} explored</span><div className="gear-control"><span>Teaching gear</span><Select value={state.gear} onValueChange={setGear}><SelectTrigger aria-label="Teaching gear"><Sparkles size={14}/><SelectValue/></SelectTrigger><SelectContent>{(['Quick','Guided','Deep'] as Gear[]).map(g=><SelectItem key={g} value={g}>{g}</SelectItem>)}</SelectContent></Select></div></div>
   {mode==='map'?<><div className="graph-surface"><div className="graph-caption"><span>THE CONNECTIONS</span><p>Choose an idea to begin.</p></div><div className="graph-scroll"><div className="graph-inner" style={{transform:`scale(${zoom})`}}><svg className="graph-lines" viewBox="0 0 1100 360" aria-hidden="true">{mapEdges.map(([a,b])=><path key={`${a}-${b}`} d={`M ${positions[a][0]} ${positions[a][1]} C ${positions[a][0]+100} ${positions[a][1]}, ${positions[b][0]-100} ${positions[b][1]}, ${positions[b][0]} ${positions[b][1]}`}/>)}</svg>{currentMap.concepts.map((c,i)=><button key={c.id} aria-label={`Learn ${c.title}`} className={'concept-node '+(c.id===concept.id?'selected ':'')+(state.visited.includes(`${currentMap.id}:${c.id}`)?'explored':'')} style={{left:positions[i][0],top:positions[i][1]}} onClick={()=>openConcept(c.id)}><span className="node-symbol">{state.visited.includes(`${currentMap.id}:${c.id}`)?<Check size={13}/>:<span/>}</span><strong>{c.title}</strong><small>{c.label}</small></button>)}</div></div><div className="graph-bottom"><span><i/> Suggested learning connections</span><div><Button variant="ghost" size="icon" aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(.65,z-.15))}><Minus size={15}/></Button><span>{Math.round(zoom*100)}%</span><Button variant="ghost" size="icon" aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(1.45,z+.15))}><Plus size={15}/></Button><Button variant="ghost" size="icon" aria-label="Reset zoom" onClick={()=>setZoom(1)}><Maximize2 size={14}/></Button></div></div></div><div className="below-map"><span><CircleHelp size={15}/>Connections are suggested learning paths, not mastery requirements.</span><button onClick={()=>setOutline(x=>!x)}><List size={15}/>{outline?'Hide':'Show'} concept list</button></div>{outline?<div className="concept-list">{currentMap.concepts.map((c,i)=><button key={c.id} onClick={()=>openConcept(c.id)}><span>0{i+1}</span><strong>{c.title}</strong><small>{c.label}</small><ArrowRight size={15}/></button>)}</div>:null}<button className="start-lesson" onClick={()=>openConcept(concept.id)}><span className="resume-icon"><BookOpen size={19}/></span><span><small>YOUR NEXT EXPLORATION</small><strong>{concept.title}</strong><p>{concept.summary}</p></span><ArrowRight size={20}/></button></>:null}
   {mode==='lesson'?<><div className="concept-path">{currentMap.concepts.map((c,i)=><button key={c.id} className={concept.id===c.id?'active':''} onClick={()=>openConcept(c.id)}><span>{i+1}</span>{c.title}</button>)}</div><article className="lesson" ref={lessonRef} onMouseUp={onSelection} onKeyUp={onSelection}><div className="lesson-meta"><span>CONCEPT {currentMap.concepts.indexOf(concept)+1} / {currentMap.concepts.length}</span><button aria-label={state.saved.includes(`${currentMap.id}:${concept.id}`)?'Unsave lesson':'Save lesson'} onClick={saveLesson}><Bookmark size={17} fill={state.saved.includes(`${currentMap.id}:${concept.id}`)?'currentColor':'none'}/></button></div><h2>{concept.title}</h2><p className="lesson-lead">{concept.summary}</p>
    {state.gear!=='Quick'||localAction==='Go deeper'||localAction==='Simpler'?<div className="lesson-copy"><h3>{localAction==='Simpler'?'In everyday terms':'Let’s build the intuition.'}</h3><p>{localAction==='Simpler'?concept.example:concept.detail}</p>{localAction==='Simpler'&&state.gear==='Deep'?<p>{concept.detail}</p>:null}</div>:null}
    {state.gear!=='Quick'||localAction==='Example'?<div className="example-block"><div><span className="example-icon"><Sparkles size={15}/></span><small>A CONCRETE EXAMPLE</small></div><p>{concept.example}</p><button onClick={()=>openBranch(concept.example,'Why?')}>Why does this work?<ArrowUpRight size={13}/></button></div>:null}
    {state.gear==='Deep'||localAction==='Go deeper'?<div className="deep-block"><h3>Connect it to the bigger picture.</h3><p>{concept.why} {currentMap.concepts[(currentMap.concepts.indexOf(concept)+1)%currentMap.concepts.length].summary}</p><p className="muted">The map’s connections offer a route for exploring these ideas. They do not mean every idea is a strict prerequisite.</p></div>:null}
    {localAction==='Visualize'?<div className="concept-visual"><small>IDEA → EXAMPLE → CONNECTION</small><div><span>{concept.title}</span><ArrowRight size={18}/><span>{concept.label}</span></div><p>{concept.example}</p></div>:null}
    {selection?<div className="selection-actions"><span>“{selection.slice(0,75)}{selection.length>75?'…':''}”</span><Button size="sm" onClick={()=>openBranch(selection)}>Explain selection<ArrowUpRight size={13}/></Button></div>:null}
    <div className="lesson-actions">{['Simpler','Go deeper','Example','Visualize'].map(a=><button className={localAction===a?'active':''} key={a} onClick={()=>setLocalAction(a)}>{a==='Simpler'?<ArrowDown size={14}/>:a==='Go deeper'?<Plus size={14}/>:a==='Example'?<Sparkles size={14}/>:<Network size={14}/>} {a}</button>)}<button onClick={()=>openBranch(concept.summary)}><GitBranch size={14}/>Explore this</button></div>
    <div className="understanding"><div><span className="eyebrow">A MOMENT TO REFLECT</span><h3>Make the idea your own.</h3><p>A short check, whenever you feel ready.</p></div><Button variant="outline" onClick={()=>{setCheckOpen(v=>!v);setAnswer(null)}}>{checkOpen?'Close check':'Check understanding'}<ArrowRight size={15}/></Button></div>
    {checkOpen?<div className="quick-check"><h3>{concept.question}</h3>{concept.choices.map((choice,i)=><button className={answer===i?(i===concept.answer?'correct':'incorrect'):''} key={choice} onClick={()=>setAnswer(i)} disabled={answer!==null}><span>{String.fromCharCode(65+i)}</span>{choice}{answer===i?<Check size={15}/>:null}</button>)}{answer!==null?<div role="status" className="check-feedback"><strong>{answer===concept.answer?'That’s right.':'Let’s look at that again.'}</strong><p>{concept.why}</p><small>This sample check does not assign a mastery score.</small><button onClick={()=>setAnswer(null)}>Try again</button></div>:null}</div>:null}
    <div className="lesson-footer"><span>Sample lesson · Select a passage to explore it.</span><button onClick={()=>{const next=currentMap.concepts[(currentMap.concepts.indexOf(concept)+1)%currentMap.concepts.length];openConcept(next.id);lessonRef.current?.scrollIntoView({behavior:'smooth',block:'start'})}}>Next concept<ArrowRight size={15}/></button></div>
   </article></>:null}
  </div>:null}
  </main>
  {branch?<aside className="exploration-panel" aria-label="Exploration panel"><header><div><GitBranch size={16}/><span>Exploration</span></div><Button variant="ghost" size="icon" aria-label="Close exploration" onClick={closeBranch}><X size={18}/></Button></header><div className="branch-breadcrumb"><button onClick={closeBranch}>Lesson</button>{crumbs.map((b,i)=><span key={b.id}><ChevronRight size={11}/><button onClick={()=>setBranchId(b.id)}>{i+1}</button></span>)}</div><div className="branch-scroll"><small className="eyebrow">{branch.mode==='Question'?'YOUR QUESTION':'A CLOSER LOOK'}</small><h2 ref={branchRef} tabIndex={-1}>{branch.mode==='Why?'?'Why does this work?':branchConcept.title}</h2><blockquote>{branch.anchor}</blockquote>{branch.note?<p className="branch-notice">{branch.note}</p>:null}<p>{branch.mode==='Why?'?branchConcept.why:branchConcept.detail}</p><div className="branch-example"><small>THINK OF IT THIS WAY</small><p>{branchConcept.example}</p></div><button className="branch-deeper" onClick={()=>openBranch(branchConcept.why,'Why?',branch.id)}>Go one level deeper <ArrowUpRight size={14}/></button><span className="branch-save"><Check size={12}/>Saved on this device</span></div><div className="branch-bottom"><form onSubmit={e=>{e.preventDefault();followBranch()}}><label className="sr-only" htmlFor="branch-question">Ask a follow-up</label><textarea id="branch-question" placeholder="What else are you wondering?" value={branch.draft} rows={2} maxLength={1000} onChange={e=>setState(s=>({...s,branches:s.branches.map(b=>b.id===branch.id?{...b,draft:e.target.value}:b)}))}/><div><small>Sample exploration</small><Button type="submit" size="icon" disabled={!branch.draft.trim()} aria-label="Send follow-up"><ArrowUp size={16}/></Button></div></form><button className="return-button" onClick={()=>branch.parent?setBranchId(branch.parent):closeBranch()}><ArrowLeft size={14}/>{branch.parent?'Back to parent exploration':'Return to your lesson'}</button></div></aside>:null}
  <Sheet open={sources} onOpenChange={setSources}><SheetContent><SheetHeader><SheetTitle>{currentMap.id.startsWith('generated:')?'Trust status':'Reading reference'}</SheetTitle><SheetDescription>{currentMap.id.startsWith('generated:')?'This graph is a structural draft awaiting retrieval and claim review.':'A place to continue learning about this sample map.'}</SheetDescription></SheetHeader><div className="source-content"><BookOpen size={26}/><h3>{currentMap.source.title}</h3><p>{currentMap.id.startsWith('generated:')?'The concepts and relationships came from the local deterministic baseline. They are useful for evaluating the learning flow, but they are not source-verified teaching.':'These are authored sample lessons, not live source-verified AI responses. The reference provides related reading; it is not a claim that each sentence has been independently verified.'}</p>{currentMap.source.url?<a href={currentMap.source.url} target="_blank" rel="noreferrer">Open reference<ExternalLink size={15}/></a>:null}</div></SheetContent></Sheet>
  <Dialog open={dialog!==null} onOpenChange={v=>{if(!v)setDialog(null)}}><DialogContent><DialogHeader><DialogTitle>{dialog==='topic'?'Keep that curiosity.':'A first look at Forma.'}</DialogTitle><DialogDescription>{dialog==='topic'?'The graph service could not complete this request. You can save the idea and explore one of the sample maps.':'This workspace combines authored sample lessons with a functional draft-graph backend.'}</DialogDescription></DialogHeader>{dialog==='topic'?<div className="dialog-body"><div className="pending-topic"><Sparkles size={18}/>{topic}</div><Button onClick={()=>{setState(s=>({...s,ideas:Array.from(new Set([...s.ideas,topic.trim()]))}));setDialog(null);setNotice('Topic saved to Knowledge maps → Ideas for later.')}}>Save topic for later<Bookmark size={15}/></Button><Button variant="outline" onClick={()=>{setDialog(null);openMap('systems')}}>Explore a sample map<ArrowRight size={15}/></Button></div>:<div className="dialog-body"><p>Try the maps, change teaching gear, select a passage, and follow an exploration without losing your place.</p><p>Progress here means <strong>explored</strong>, not mastered. Your saved lessons, branches, and preferences stay in this browser. Live model teaching, source retrieval, and account sync are the next backend layers.</p><Button onClick={()=>setDialog(null)}>Back to learning<ArrowRight size={15}/></Button></div>}</DialogContent></Dialog>
  {notice?<div className="toast-message" role="status"><Check size={16}/>{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss notification"><X size={14}/></button></div>:null}
 </SidebarProvider>
}
